// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FButton: typeof import('./../src/components/FButton.vue')['default']
    FButtonGroup: typeof import('./../src/components/FButtonGroup.vue')['default']
    Flogo: typeof import('./../src/components/Flogo.vue')['default']
    FSvgIcon: typeof import('./../src/components/FSvgIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
